### ISSUE TITLE
Moving visutalization and MuseScore features to a separate repository

### ISSUE THREAD

**Issue by aminya** [JuliaMusic/MusicManipulations.jl#45]
I think, separating visualization and MuseScore interfacing features of this repository should be moved to a separate repository so that all the other packages can use that as their dependency. 

For example, MusicXML doesn't need any music manipulation features, but it needs visualization and interfacing with MuseScore.

Also, if we separate these features, we can use BinaryProvider to automatically install MuseScore (or other visualization software from other languages). Adding these to MuiscManipulation.jl makes it complex for no reason, but in a separate package aimed specifically at this, we will have much more freedom for providing external software.

**Comment by aminya** [comment]
Some of the visualization features that can be added to that repository can be:

Using Cxxwrap:
https://github.com/projectM-visualizer/projectm

Using Pycall:
https://github.com/dmpayton/python-fretboard

Using MATLAB.jl:
https://github.com/JuliaMusic/1.1

**Comment by Datseris** [comment]
While in general you have a valid point that I agree with, I must address:

> Also, if we separate these features, we can use BinaryProvider to automatically install MuseScore (or other visualization software from other languages).

For "reasons", I feel 99% certain that this will not be as smooth you imagine :D You're welcome to try this and inform us how it went  though!

Okay, then I'll move all visualization related functionality to `MusicVisualizations.jl`, under the mask "Providing visualization features for the packages of JuliaMusic". How does it sound?

**Comment by aminya** [comment]
> Okay, then I'll move all visualization related functionality to `MusicVisualizations.jl`, under the mask "Providing visualization features for the packages of JuliaMusic". How does it sound?

That sounds good! 😃 

> For "reasons", I feel 99% certain that this will not be as smooth you imagine :D You're welcome to try this and inform us how it went though!

I know it is not easy, but it will be a great enhancement! We can learn from other packages that have done these before.

**Comment by Datseris** [comment]
Great, with this I will be able to release MusicManipulations.jl v1.0, which I wanted for a long time but all the musescore stuff not working was keeping it back.
