### ISSUE TITLE
possible test failure in upcoming Julia version 1.5

### ISSUE THREAD

**Issue by rfourquet** [JuliaMusic/MusicManipulations.jl#54]
A PkgEval run for a [PR](https://github.com/JuliaLang/julia/pull/35078) which changes the generated numbers for `randn!` indicates that the tests of this package might fail in Julia 1.5 (and on Julia current master). Apologies if this is a false positive.
cf. 
https://github.com/JuliaCI/NanosoldierReports/blob/7de24e455342298cbef56826b5827f0d7640d2c1/pkgeval/by_hash/b89e35c_vs_098ef24/logs/MusicManipulations/1.5.0-DEV-71a4a114c2.log

**Comment by Datseris** [comment]
Thanks a lot for opening this. Could you please link me to the new `randn!` ? I certainly also have to add a `seed!` to the tests.

**Comment by rfourquet** [comment]
The tests fail also in another [PkgEval run](https://github.com/JuliaCI/NanosoldierReports/blob/ab6676206b210325500b4f4619fa711f2d7429d2/pkgeval/by_hash/52c2272_vs_47c55db/logs/MusicManipulations/1.5.0-DEV-87d2a04de3.log) for a change in `rand(a:b)` (https://github.com/JuliaLang/julia/pull/29240). 

Also, you might be interested in using the new [StableRNGs.jl](https://github.com/rfourquet/StableRNGs.jl) registered package, which provides guaranteed stable streams of random numbers across Julia releases.

**Comment by Datseris** [comment]
I can't reproduce these failings anymore in Julia 1.5.0-rc1. Seems the problem fixed itself :D
