### ISSUE TITLE
Humanizer via addition of pink-noise

### ISSUE THREAD

**Issue by Datseris** [JuliaMusic/MusicManipulations.jl#56]
Research shows that human timing fluctuations are not white noise, but instead pink noise with varying exponents from -0.5 to -1.5.

A simple function `humanize!` could first generate such noise using e.g. ARFIMA.jl and then add it to the note positions.

**Comment by michiboo** [comment]
Hello! can I have a go at this issue?

**Comment by michiboo** [comment]
@Datseris  I have created a PR for this issue, but I am not sure if I got it correctly, please review it when you have time! Thanks!

**Comment by Datseris** [comment]
> Hello! can I have a go at this issue?

Hi, absolutely! Why not?!

**Comment by michiboo** [comment]
@Datseris I don't get how I can get the varying exponents from -0.5 to -1.5 from arfima.jl... do I pass it as parameters?

**Comment by Datseris** [comment]
Nope. I don't know either :D ARFIMA with fractional value for `d` can generate power-law correlated timeseries, but to my knolwedge, there isn't a "simple" way to connect the ARFIMA parameters with the power-law slope. Also, ARFIMA doesn't really generate "pure" power-laws...

**Comment by michiboo** [comment]
ah ok I will try to see what I can get! :)

**Comment by Datseris** [comment]
Don't worry too much about getting a perfect power-law for now. Let's first get the interface going well, and then we can think about the specific noise in detail.

**Comment by michiboo** [comment]
@Datseris  Hi is the ARFIMA package on JuliaRegistries? If not I could try open a PR to add JuliaRegistries, at the moment there is some CI issues with the package as it cannot found it on the Registries.

**Comment by Datseris** [comment]
Hi @michiboo ,

Nope, it is not registered yet. Sorry for forgetting this! I'll register today (but it will take a couple of days until its public). In the meantime you can address the rest of the comments in #57 and I'll get to it.

Also, do you mind if we continue this discuss in PR #57 ? It makes it easier for me to stay organized :)

**Comment by michiboo** [comment]
@Datseris  Ok thanks! I will discuss on there.
